database:
  host: localhost
  port: 3306
  name: GlobalWarming
  username: user
  password: pass
  update-interval: 300
worlds:
    - world
associations:
  - world_nether:world
  - world_the_end:world