bounty:
  max-created-per-player: 5
climate:
  default-sea-level: 63
  default-ice-level: 0.0
  default-snow-level: 0.0
  default-farm-yield-fitness: 100.0
  default-mob-fitness: 100.0
  default-temperature: 14.0
  low-temperature-ubound: 13.75
  high-temperature-lbound: 14.25
commands:
  spam-interval: 60
database:
  host: localhost
  port: 3306
  name: GlobalWarming
  username: user
  password: pass
  interval: 300
notification:
  interval: 6000
  duration: 300
scoreboard:
  interval: 20